server:
  port: 9000

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
  webflux:
    static-path-pattern: /webjars/**
  web:
    resources:
      add-mappings: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

jwt:
  secret: VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCBsb25nIHNlY3JldCBrZXkgZm9yIEpXVCBzaWduYXR1cmU=



springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: ms-auth
        url: /swagger/ms-auth/v3/api-docs
      - name: ms-usuarios
        url: /swagger/ms-usuarios/v3/api-docs
      - name: ms-pedidos
        url: /swagger/ms-pedidos/v3/api-docs
      - name: ms-pagos
        url: /swagger/ms-pagos/v3/api-docs
      - name: ms-precios
        url: /swagger/ms-precios/v3/api-docs
      - name: ms-envios
        url: /swagger/ms-envios/v3/api-docs
      - name: ms-notificaciones
        url: /swagger/ms-notificaciones/v3/api-docs
      - name: ms-resenas
        url: /swagger/ms-resenas/v3/api-docs
  api-docs:
    enabled: false