spring.application.name=ms-usuarios

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@oj1jsry5oq5a4c36_high?TNS_ADMIN=\Users\Eduardo Cossio\Desktop\w_proyecto
spring.datasource.username=ADMIN
spring.datasource.password=Duocuc12345.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG
logging.level.java.sql=DEBUG

spring.jpa.hibernate.ddl-auto=update