# Ajusta el nombre y puerto para cada uno (ej. 8090, 8091, 8092)
spring.application.name=ms-envios
server.port=8090

# 1. SEGURIDAD H2: Acceso bloqueado desde el exterior
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# 2. BASE DE DATOS: Modo validación (más seguro)
spring.datasource.url=jdbc:h2:mem:enviosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 3. HIBERNATE: Solo validar (no modificar tablas automáticamente)update
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# 4. EUREKA: Registro
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# SWAGGER
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html