spring.application.name=ms-pedidos
server.port=8084

# Oracle con Wallet
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@proyectotcg_high?TNS_ADMIN=C:/w_proyecto
spring.datasource.username=user_ms_pedidos
spring.datasource.password=Duocuc12345.

# JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Hikari
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

# Feign logging
logging.level.feign=DEBUG

#Feign timeouts
feign.client.config.default.connect-timeout=3000
feign.client.config.default.read-timeout=5000

#Resilience4j
feign.circuitbreaker.enabled=true

resilience4j.circuitbreaker.instances.ms-catalogo.sliding-window-size=10
resilience4j.circuitbreaker.instances.ms-catalogo.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ms-catalogo.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.ms-catalogo.permitted-number-of-calls-in-half-open-state=3

resilience4j.circuitbreaker.instances.ms-inventario.sliding-window-size=10
resilience4j.circuitbreaker.instances.ms-inventario.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ms-inventario.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.ms-inventario.permitted-number-of-calls-in-half-open-state=3

springdoc.enable-hateoas=false