spring.application.name=eureka-server

# puerto estandar de eureka
server.port=8761

# Configuracion para que no se registre a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.enable-self-preservation=false
