# 1. Identificación del Microservicio
spring.application.name=ms-inventario
server.port=8088

# 2. Configuración de Oracle con Wallet
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@proyectotcg_high?TNS_ADMIN=C:/w_proyecto
spring.datasource.username=user_ms_inventario
spring.datasource.password=Duocuc12345.

# 3. JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Registro en Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# 5. Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# 6. Logs
logging.level.com.ms_inventario=DEBUG
logging.level.feign=DEBUG